### ISSUE TITLE
Getting Error while installing SQL Watch.

### ISSUE THREAD

**Issue by SatishShelke** [marcingminski/sqlwatch-docs#12] opened 2020-08-13 12:02 UTC
I am getting below error while installing SQLwatch package. Tried importing package from SSMS Same error reported while package deployment.

PS C:\windows\system32> Install-DbaSqlWatch MyserverName
WARNING: [17:24:30][Publish-DbaDacPackage] Deployment failed | Could not deploy package.
Error SQL72014: .Net SqlClient Data Provider: Msg 50000, Level 16, State 1, Procedure dbo.usp_sqlwatch_internal_run_job, Line 61 Job 'SQLWATCH-INTERNAL-CHECKS' has not finished successfuly or the state
is not known.
Error SQL72045: Script execution error.  The executed script:
BEGIN TRANSACTION;

MERGE INTO dbo.sqlwatch_config_sql_instance
 AS target
USING (SELECT @@SERVERNAME AS [servername],
              0 AS [repo_collector_is_active]) AS source ON target.sql_instance = source.[servername]
WHEN NOT MATCHED THEN INSERT (sql_instance, [repo_collector_is_active]) VALUES (source.[servername], source.[repo_collector_is_active]);

MERGE INTO [dbo].[sqlwatch_meta_server]
 AS target
USING (SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')) AS [physical_name],
              CONVERT (sysname, @@SERVERNAME) AS [servername],
              CONVERT (sysname, @@SERVICENAME) AS [service_name],
              CONVERT (VARCHAR (50), local_net_address) AS [local_net_address],
              CONVERT (VARCHAR (50), local_tcp_port) AS [local_tcp_port],
              DATEDIFF(mi, GETUTCDATE(), GETDATE()) AS [utc_offset_minutes],
              @@VERSION AS [sql_version]
       FROM   sys.dm_exec_connections
       WHERE  session_id = @@spid) AS source ON target.[se

ComputerName : MyServerName
InstanceName : MSSQLSERVER
SqlInstance  : MyServerName
Database     : SQLWATCH
Status       : (Failed)

**Comment by marcingminski** [comment] 2020-08-20 22:20
Hi, For the future, this is the repository for the SQLWATCH documentation and not monitored. If your issues relate to the SQLWATCH application, please head over to https://github.com/marcingminski/sqlwatch or check out our user forum for help: https://meta.sqlwatch.io/

As for your error, it looks like a duplicate of https://github.com/marcingminski/sqlwatch/issues/198

**Closed by marcingminski** 2020-08-20 22:20 UTC
